// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuqlmdyxdzptttfnbidr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1cWxtZHl4ZHpwdHR0Zm5iaWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDgwOTEsImV4cCI6MjA2NjE4NDA5MX0.PEAmxTAkAbk7zQ9TSIZDFyDFS2Ipq21PZSyqDfDPNg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);